### PR TITLE
eip-0003: BIP-44 standard for Ergo Platform

### PR DESCRIPTION
**Pull request by gagarin55**
Before acceptance we need to discuss **coint_type** number and make PR to SLIP-0044 repository

### CODE REVIEW

**Comment by robkorn** [comment]
This may be a little bit of overly pedantic fun, but maybe we can make the *coin_type* number be `ergo` in ascii and summed?
`101 + 114 + 103 + 111 = 429`

`429` is still available based on the [list](https://github.com/satoshilabs/slips/blob/master/slip-0044.md), so it is doable.

**Comment by gagarin55** [comment]
Why not? **429** might be good idea, only if they (SLIP-44) accept it

**Comment by kushti** [comment]
Looks fine! If there are no more comments, lets merge?!

**Comment by gagarin55** [comment]
Let's wait SLIP-0044 changes approval - https://github.com/satoshilabs/slips/pull/794

**Pull request merged**
